name: 'Build and publish images for multiple architectures'

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: multiarch-test
  TARGET_ARCHS: amd64,ppc64le
jobs:
  multiarch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU static binaries for multiple architectures.
      uses: docker/setup-qemu-action@master
      with:
        platforms: ${{ env.TARGET_ARCHS }}

    - name: Build images for multiple architectures
      id: build-images
      uses: redhat-actions/buildah-build@v2 
      with:
        archs: ${{ env.TARGET_ARCHS }}
        image: ${{ env.IMAGE_NAME }}
        tags: ${{ github.sha }}
        containerfiles: |
          ./Dockerfile
    
    - name: Ensure manifest was built.
      run: |
        buildah manifest inspect localhost/${{ env.IMAGE_NAME }}:${{ github.sha }}

    - name: Push to target push registry.
      id: push-to-registry
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ env.IMAGE_NAME }}
        tags: ${{ github.sha }}
        registry: quay.io/${{ secrets.REGISTRY_REPOSITORY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}