name: 'Build and publish images for multiple architectures'

on:
  push:
    branches:
      - master

jobs:
  multiarch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU static binaries for multiple architectures.
      uses: docker/setup-qemu-action@master
      with:
        platforms: amd64,ppc64le

    - name: Build images for multiple architectures
      id: build-images
      uses: redhat-actions/buildah-build@v2 
      with:
        image: my-new-image
        tags: ${{ github.sha }}
        containerfiles: |
          ./Dockerfile
    
    - name: List images
      run: |
        buildah images
        buildah manifest inspect localhost/my-new-image

      # - name: Push to target push registry.
      #   id: push-to-registry
      #   uses: redhat-actions/push-to-registry@v2
      #   with:
      #     image: ${{ steps.build-images.outputs.image }}
      #     tags: ${{ steps.build-images.outputs.tags }}
      #     registry: quay.io #quay.io/quay-user
      #     username: ${{ secrets.REGISTRY_USER}}
      #     password: ${{ secrets.REGISTRY_PASSWORD }}