name: 'Build and publish images for multiple architectures'

on:
  push:
    # branches:
      # - master
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-alpha[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-beta[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'

env:
  IMAGE_NAME: multiarch-test
  TARGET_ARCHS: amd64,ppc64le
jobs:
  multiarch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set Env Tags
      run: echo RELEASE_TAG=$(echo $GITHUB_REF | cut -d '/' -f 3) >> $GITHUB_ENV

    - name: Set up QEMU static binaries for multiple architectures.
      uses: docker/setup-qemu-action@master
      with:
        platforms: ${{ env.TARGET_ARCHS }}

    - name: Build images for multiple architectures
      id: build-images
      uses: redhat-actions/buildah-build@v2 
      with:
        archs: ${{ env.TARGET_ARCHS }}
        image: ${{ env.IMAGE_NAME }}
        # tags: ${{ github.sha }}
        tags: ${{ env.RELEASE_TAG }}
        containerfiles: |
          ./Dockerfile
    
    - name: Ensure manifest was built.
      run: |
        buildah manifest inspect localhost/${{ env.IMAGE_NAME }}:${{ env.RELEASE_TAG }}

    - name: Push to target push registry.
      id: push-to-registry
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ env.IMAGE_NAME }}
        # tags: ${{ github.sha }}
        tags: ${{ env.RELEASE_TAG }}
        registry: quay.io/${{ secrets.REGISTRY_REPOSITORY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}